version: '3.8'

services:
  # Application Spring Boot
  app:
    build: .
    container_name: spring_app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hackbou.com:5432/flux-transaction-v1
      - SPRING_DATASOURCE_USERNAME=hackbou
      - SPRING_DATASOURCE_PASSWORD=npmstart
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8085:8085"